### PR TITLE
Refactor top-app-bar into top-app-bar, top-app-bar-fixed, and top-app…

### LINKED ISSUE #329: <mwc-top-app-bar> needs a way to pad content below
Content below a top-app-bar needs to be top-padded to account for the height of the fixed position bar, or else it will look like this, with the content hidden behind the bar:

In standard MDC, users have direct access to classes like `mdc-top-app-bar--short-fixed-adjust` which specify the padding needed for a given bar configuration. MWC users do not have access to these classes, since they are in component shadow DOM.

We have a few options:

1. Export a `CSSResult` from `mwc-top-app-bar.js` that provides these classes (or equivalents) that users can apply to their document or shadow root and then reference in their content. Something like:

```css
.topAppBarPadding {
  padding-top: 64px; /* $mdc-top-app-bar-row-height */
}
@media (max-width: 599px) { /* $mdc-top-app-bar-mobile-breakpoint */
  .topAppBarPadding {
    padding-top: 56px; /* $mdc-top-app-bar-mobile-row-height */
  }
}
.topAppBarPaddingDense {
  padding-top: 48px; /* $mdc-top-app-bar-dense-row-height */
}
.topAppBarPaddingProminent {
  padding-top: 128px; /* $mdc-top-app-bar-prominent-row-height */
}
```

2) Add a `<slot>` to `<mwc-top-app-bar>` to hold user content, and the element automatically applies the right style. This seems like the more user-friendly option, but it does mean that the element becomes more of a full-layout-wrapper, which seems not ideal. Maybe worth the tradeoff, though?

### LINKED ISSUE #351: <mwc-top-app-bar> needs a way to set background color

### PR DESCRIPTION
**Pull request by azakus**
…-bar-short

- [x] Remove fixed and short options from mwc-top-app-bar
- [x] remove `centerTitle` from mwc-top-app-bar
- [x] mwc-top-app-bar README
- [x] mwc-top-app-bar-fixed
- [x] mwc-top-app-bar-fixed README
- [x] mwc-top-app-bar-short
- [x] mwc-top-app-bar-short README
- [ ] fix tests
- [ ] update CHANGELOG

Fixes #329 
Fixes #351

### CODE REVIEW

**Comment by azakus** [comment]
Cheating a bit by forking the foundation change I made in https://github.com/material-components/material-components-web/pull/5009, but it was the only good way to fix the scrolling bug with the `short` component.

File: packages/base/src/utils.ts [hunk 1]
```diff
@@ -45,3 +45,36 @@ export function addHasRemoveClass(element: HTMLElement) {
...
 }
+
+/**
+ * Event listeners suport `passive` option
+ */
+export let supportsPassiveEventListener = false;
+/**
+ * Event listeners support `once` option
+ */
+export let supportsOnceEventListener = false;
```
Comment (aomarks) [inline packages/base/src/utils.ts]: Doesn't look like we're using the `once` or `capture` probes, remove them for now? Or do you expect we'll need them for something else sometime soon?

File: packages/top-app-bar/src/mwc-top-app-bar-base-base.ts [hunk 2]
```diff
@@ -0,0 +1,144 @@
...
+See the License for the specific language governing permissions and
+limitations under the License.
+*/
+import {addHasRemoveClass, BaseElement, classMap, html, property, query} from '@material/mwc-base/base-element';
+import {supportsPassiveEventListener} from '@material/mwc-base/utils';
+import {MDCTopAppBarAdapter} from '@material/top-app-bar/adapter';
+import {strings} from '@material/top-app-bar/constants';
+import MDCTopAppBarBaseFoundation from '@material/top-app-bar/foundation';
+
+export const passiveEventListener =
```
Comment (aomarks) [inline packages/top-app-bar/src/mwc-top-app-bar-base-base.ts]: How about `passiveEventOptionsIfSupported`

File: packages/top-app-bar-fixed/README.md [hunk 3]
```diff
@@ -0,0 +1,136 @@
...
+| `navigationIcon` | `<mwc-icon-button>` elements to use for the left icon.
+| `title` | Element that will be used as the title text.
+| _default_ | Scrollable content to display under the bar. This may be the entire application.
+
+### Properties/Attributes
+| Name | Type | Default | Description
+| ---- | ---- | ------- | -----------
+| `dense` | `boolean` | `false` | Makes the bar a little smaller for higher density applications.
+| `prominent` | `boolean` | `false` | Makes the bar much taller, can be combined with `dense`.
+| `scrollTarget` | `HTMLElement | Window` | `window` | Element used to listen for `scroll` events.
```
Comment (aomarks) [inline packages/top-app-bar-fixed/README.md]: Missing a closing backtick on `HTMLElement` and opening one for `Window` here, same for the other 2 READMEs.

File: packages/top-app-bar-short/README.md [hunk 4]
```diff
@@ -0,0 +1,102 @@
...
+  --mdc-theme-on-primary: black;
+}
+```
+
+## API
+
+### Slots
+| Name | Description
+| ---- | -----------
+| `actionItems` | One `<mwc-icon-button>` elements to use for action icons on the right side.
```
Comment (aomarks) [inline packages/top-app-bar-short/README.md]: s/elements/element

File: packages/top-app-bar/README.md [hunk 5]
```diff
@@ -1,64 +1,136 @@
...
-## Supported Browsers
-
-The last 2 versions of all modern browsers are supported, including
-Chrome, Safari, Opera, Firefox, Edge. In addition, Internet Explorer 11 is also supported.
\ No newline at end of file
+### Slots
+| Name | Description
+| ---- | -----------
+| `actionItems` | A number of `<mwc-icon-button>` elements to use for action icons on the right side.
+| `navigationIcon` | `<mwc-icon-button>` elements to use for the left icon.
```
Comment (aomarks) [inline packages/top-app-bar/README.md]: s/elements/element

File: packages/top-app-bar-short/src/mdc-top-app-bar-short-foundation.ts [hunk 6]
```diff
@@ -0,0 +1,119 @@
...
+ * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
+ * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
+ * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
+ * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
+ * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
+ * THE SOFTWARE.
+ */
+
+/* NOTE: Delete this after
+ * https://github.com/material-components/material-components-web/pull/5009
```
Comment (aomarks) [inline packages/top-app-bar-short/src/mdc-top-app-bar-short-foundation.ts]: Looks like this MDC PR was approved, so can probably remove before merging this PR? I guess we'd need a release though, what's the MDC release schedule?

File: packages/top-app-bar-fixed/README.md [hunk 7]
```diff
@@ -0,0 +1,136 @@
...
+```
+
+## API
+
+### Slots
+| Name | Description
+| ---- | -----------
+| `actionItems` | A number of `<mwc-icon-button>` elements to use for action icons on the right side.
+| `navigationIcon` | `<mwc-icon-button>` elements to use for the left icon.
+| `title` | Element that will be used as the title text.
```
Comment (e111077) [inline packages/top-app-bar-fixed/README.md]: Does this work with anything other than div? like will span style correctly, etc.

File: packages/top-app-bar-fixed/src/top-app-bar-fixed-base.ts [hunk 8]
```diff
@@ -0,0 +1,40 @@
...
+import MDCFixedTopAppBarFoundation from '@material/top-app-bar/fixed/foundation';
+
+export class TopAppBarFixedBase extends TopAppBarBase {
+  protected mdcFoundation!: MDCFixedTopAppBarFoundation;
+
+  protected mdcFoundationClass = MDCFixedTopAppBarFoundation;
+
+  protected get barClasses() {
+    return {
+      ...super.barClasses, 'mdc-top-app-bar--fixed': true,
```
Comment (e111077) [inline packages/top-app-bar-fixed/src/top-app-bar-fixed-base.ts]: Open Question: Should we be using these classnames directly or accessing them from their respective `constants.ts` files?

File: packages/top-app-bar/src/mwc-top-app-bar-base-base.ts [hunk 9]
```diff
@@ -0,0 +1,144 @@
...
+   * classMap map for classes on the bar
+   */
+  protected abstract barClasses: ClassInfo;
+
+  /**
+   * classMap map for classes on the content slot
+   */
+  protected abstract contentClasses: ClassInfo;
+
+  // TODO(sorvell): MDC decorates the navigation icon and action items with
```
Comment (e111077) [inline packages/top-app-bar/src/mwc-top-app-bar-base-base.ts]: is sorvell still working on this? Perhaps file a bug instead since we don't really have TODO infra in our project

File: packages/top-app-bar/src/mwc-top-app-bar-base-base.ts [hunk 10]
```diff
@@ -0,0 +1,144 @@
...
+  // ripples. Since these are slotted items here, the assumption is that the
+  // user brings a web component with a ripple if rippling is desired.
+  protected render() {
+    return html`
+      <header class="mdc-top-app-bar ${classMap(this.barClasses)}">
+      <div class="mdc-top-app-bar__row">
+        <section class="mdc-top-app-bar__section mdc-top-app-bar__section--align-start" id="navigation">
+          <slot name="navigationIcon" @click=${
+        this.handleNavigationClick}></slot>
```
Comment (e111077) [inline packages/top-app-bar/src/mwc-top-app-bar-base-base.ts]: did you run the formatter?

File: packages/top-app-bar-short/README.md [hunk 11]
```diff
@@ -0,0 +1,102 @@
+# `<mwc-top-app-bar-short>` [![Published on npm](https://img.shields.io/npm/v/@material/mwc-top-app-bar-short.svg)](https://www.npmjs.com/package/@material/mwc-top-app-bar-short)
+
+> IMPORTANT: The Material Web Components are a work in progress and subject to
+> major changes until 1.0 release.
+
+Short Top App Bars are a container for items such as application title, navigation icon, and an action item that shrinks into the corner.
+
```
[the remark this answers is not in the document]
Comment (azakus) [reply packages/top-app-bar-short/README.md]: I'm not 100% sure what to do here. Short and Fixed essentially look the same as the standard component at rest.

File: packages/top-app-bar-short/README.md [hunk 12]
```diff
@@ -0,0 +1,102 @@
...
+> tooling step is required to resolve *bare module specifiers*, as well as
+> transpilation and polyfills for Edge and IE11. See
+> [here](https://github.com/material-components/material-components-web-components#quick-start)
+> for detailed instructions.
+
+## Example Usage
+
+### Standard
+
+<img src="images/standard.png" height="542px">
```
[the remark this answers is not in the document]
Comment (azakus) [reply packages/top-app-bar-short/README.md]: Similar to the other comment, there's no good way to tell at rest what the top-app-bar does.

[the remark this answers is not in the document]
Comment (azakus) [reply packages/top-app-bar-short/README.md]: No, I added that. I'll remove it.

File: packages/base/src/utils.ts (hunk 1 above)
Comment (azakus) [reply packages/base/src/utils.ts]: I can probably remove them

File: packages/top-app-bar-short/README.md (hunk 12 above)
[the remark this answers is not in the document]
Comment (aomarks) [reply packages/top-app-bar-short/README.md]: That's true regardless of whether there's text or not in the screenshot, right?

File: packages/top-app-bar-fixed/README.md (hunk 3 above)
Comment (azakus) [reply packages/top-app-bar-fixed/README.md]: This is the exact typing of `scrollTarget`:  `HTMLElement|Window`. How do we want to handle this for documentation?

File: packages/top-app-bar-fixed/src/top-app-bar-fixed-base.ts (hunk 8 above)
Comment (azakus) [reply packages/top-app-bar-fixed/src/top-app-bar-fixed-base.ts]: Good question. I'm OK using the css classes out of the foundation.

File: packages/top-app-bar/src/mwc-top-app-bar-base-base.ts (hunk 10 above)
Comment (azakus) [reply packages/top-app-bar/src/mwc-top-app-bar-base-base.ts]: I did!

File: packages/top-app-bar/src/mwc-top-app-bar-base-base.ts (hunk 9 above)
Comment (azakus) [reply packages/top-app-bar/src/mwc-top-app-bar-base-base.ts]: Oh I thought I had removed that line

File: packages/top-app-bar-short/README.md (hunk 12 above)
[the remark this answers is not in the document]
Comment (azakus) [reply packages/top-app-bar-short/README.md]: Yes. Maybe the right approach is to show the "unscrolled" and "scrolled" styling?

File: packages/base/src/utils.ts [hunk 13]
```diff
@@ -45,3 +45,36 @@ export function addHasRemoveClass(element: HTMLElement) {
...
+/**
+ * Event listeners suport `capture` option
+ */
+export let supportsCaptureEventListener = false;
+
+(() => {
```
[the remark this answers is not in the document]
Comment (azakus) [reply packages/base/src/utils.ts]: Not if we only have `supportsPassiveEventListener`.

File: packages/top-app-bar-fixed/README.md (hunk 3 above)
Comment (aomarks) [reply packages/top-app-bar-fixed/README.md]: I think the bar is fine for the union, it's just that it's confusing the markdown parser. Needs an escape or something maybe?

image

File: packages/base/src/utils.ts (hunk 13 above)
[the remark this answers is not in the document]
Comment (aomarks) [reply packages/base/src/utils.ts]: Why would you need an IIFE anyway? Just curious, it seems like it's just some non-exported module scoped variables, which is fine.

File: packages/top-app-bar-fixed/src/top-app-bar-fixed-base.ts (hunk 8 above)
Comment (e111077) [reply packages/top-app-bar-fixed/src/top-app-bar-fixed-base.ts]: I'll bring this up in our next meeting

File: packages/top-app-bar-fixed/README.md (hunk 7 above)
Comment (azakus) [reply packages/top-app-bar-fixed/README.md]: A span work work as well, as the slot is inside of a `flex`d span.

I'm wondering if this even needs to be a slot, or if it should instead just be an attribute.

File: packages/base/src/utils.ts (hunk 13 above)
[the remark this answers is not in the document]
Comment (azakus) [reply packages/base/src/utils.ts]: You're right. Removing

File: packages/top-app-bar/src/mwc-top-app-bar-base-base.ts (hunk 2 above)
Comment (azakus) [reply packages/top-app-bar/src/mwc-top-app-bar-base-base.ts]: Done.

File: packages/top-app-bar-fixed/README.md (hunk 3 above)
Comment (azakus) [reply packages/top-app-bar-fixed/README.md]: Great, `vscode`'s parser works

File: packages/top-app-bar-short/README.md (hunk 11 above)
[the remark this answers is not in the document]
Comment (azakus) [reply packages/top-app-bar-short/README.md]: Added gifs to all the READMEs to show the interaction

File: packages/top-app-bar-fixed/README.md [hunk 14]
```diff
@@ -0,0 +1,138 @@
...
+    <mwc-icon-button icon="file_download" slot="actionItems"></mwc-icon-button>
+    <mwc-icon-button icon="print" slot="actionItems"></mwc-icon-button>
+    <mwc-icon-button icon="favorite" slot="actionItems"></mwc-icon-button>
+    <div><!-- content --></div>
+</mwc-top-app-bar-fixed>
+```
+
+### Prominent and Dense
+
+<img src="images/prominent_and_dense.png" height="96px">
```
Comment (aomarks) [inline packages/top-app-bar-fixed/README.md]: The title cuts off in this screenshot.

File: packages/top-app-bar-fixed/README.md [hunk 15]
```diff
@@ -0,0 +1,138 @@
+# `<mwc-top-app-bar-fixed>` [![Published on npm](https://img.shields.io/npm/v/@material/mwc-top-app-bar-fixed.svg)](https://www.npmjs.com/package/@material/mwc-top-app-bar-fixed)
+
+> IMPORTANT: The Material Web Components are a work in progress and subject to
+> major changes until 1.0 release.
+
+Fixed Top App Bars are a container for items such as application title, navigation icon, and action items that are always visible.
+
+![](images/fixed.gif)
```
Comment (aomarks) [inline packages/top-app-bar-fixed/README.md]: The gifs are awesome, exactly what's needed to show the difference between the three layouts. I can't help myself notice these nits though...

- It looks very blurry on my retina screen (whereas the other screenshots below it look perfect). Was it recorded on a low dpi screen?
- I think it'd look better without the mouse cursor visible (put the mouse lower down so it's not in the crop?)
- I think it'd look better if the text was left padded, and probably a lower font weight (e.g. like in this screenshot from the spec?)

image

File: packages/top-app-bar-fixed/README.md (hunk 14 above)
Comment (azakus) [reply packages/top-app-bar-fixed/README.md]: I think I can remove the `Fixed` part from these, and that should fix it.

Comment (azakus) [reply packages/top-app-bar-fixed/README.md]: Done

File: packages/top-app-bar-fixed/README.md (hunk 15 above)
Comment (azakus) [reply packages/top-app-bar-fixed/README.md]: Didn't change the font weight, but a `16px` padding left and right looks a lot better.

Comment (aomarks) [reply packages/top-app-bar-fixed/README.md]: Looks better! Still looks blurry though.

Comment (azakus) [reply packages/top-app-bar-fixed/README.md]: Hmm, this is only looking blurry on a high DPI display. I think the tool I'm using is just not capturing at 2x? Or maybe this is as good as I can get from it.

There are alternate options, but maybe this is acceptable for now and I can look into improving the gif quality in the future?

Comment (aomarks) [reply packages/top-app-bar-fixed/README.md]: Yeah looks like licecap might be bad at doing high dpi: https://github.com/justinfrankel/licecap/issues/9. Ok, if you don't want to spend more time on it, your call.

**Comment by azakus** [comment]
> LGTM, I guess file issues for fixing the gif, and for deleting the forked foundation once MDC releases?

Filed https://github.com/material-components/material-components-web-components/issues/411 and https://github.com/material-components/material-components-web-components/issues/410 to track
