### PR TITLE
fix(slider): min and max update UI correctly

### LINKED ISSUE #1079: Slider min/max is not respected
**Describe the bug**
When setting min/max on a slider, the bounds are not respected. Dragging the thumb sets values from 0-100 regardless of min/max

**To Reproduce**
```js
render() {
  return html`
    <mwc-slider .min="2000" .max="2050" pin step="1" .value="2020"></mwc-slider>
 `;
}
```

https://webcomponents.dev/edit/H9vYUiJDCU1ilo7ELKE1

**Expected behavior**
Values out of bounds should not be set. Dragging the thumb should move the slider between bounds.

**Browser Version (please complete the following information):**
 - OS: mac
 - Browser: FF
 - Version: 75 series

### PR DESCRIPTION
**Pull request by e111077**
fixes #1079

### CODE REVIEW

File: packages/slider/src/mwc-slider-base.ts [hunk 1]
```diff
@@ -153,6 +157,27 @@ export class SliderBase extends FormElement {
     }
   }
 
+  updated(changed: PropertyValues) {
+    const minChanged = changed.has('min');
+    const maxChanged = changed.has('max');
+
+    if (minChanged && maxChanged) {
+      if (this.max < this.mdcFoundation.getMin()) {
```
Comment (rowanc1) [inline packages/slider/src/mwc-slider-base.ts:165]: I am getting some weird behavior when my min is greater than 100 when both min/max are set. The max gets overwritten.

**Comment by bennypowers** [comment]
At the risk of being a nudnik, is there an indication of when this will be released?

**Comment by e111077** [comment]
We should be discussing a release tomorrow so likely EoW
